# Generated by Django 5.0.6 on 2024-06-20 15:02

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Категория"
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Husband",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
                ("m_count", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TagsPosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
        migrations.CreateModel(
            name="Women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, message="Минимум 5 символов"
                            ),
                            django.core.validators.MaxLengthValidator(
                                100, message="Максимум 100 символов"
                            ),
                        ],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/%Y/%m/%d",
                        verbose_name="Фото",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Статья")),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        choices=[(False, "Черновик"), (True, "Опубликованно")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="women.category",
                    ),
                ),
                (
                    "husband",
                    models.OneToOneField(
                        blank=True,
                        null=-1,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="woman",
                        to="women.husband",
                    ),
                ),
                ("tags", models.ManyToManyField(default=0, to="women.tagsposts")),
            ],
            options={
                "verbose_name": "Известные женщины",
                "verbose_name_plural": "Известные женщины",
                "ordering": ["-time_create"],
                "indexes": [
                    models.Index(
                        fields=["-time_create"], name="women_women_time_cr_9f33c2_idx"
                    )
                ],
            },
            managers=[
                ("publushed", django.db.models.manager.Manager()),
            ],
        ),
    ]
